### ISSUE TITLE
Убрать создание engine, Session при каждом reconnect

### ISSUE THREAD

**Issue by grigoriev-semyon** [profcomff/print-bot#33]
https://github.com/profcomff/print-vkbot/blob/e59e7676757b28ce6711e4bc5c98cbd66149c0ed/src/db.py#L47

Это ломает нам БД 
```
2023-08-24 19:53:33.463 UTC [1683700] FATAL:  terminating connection due to idle-session timeout
```

**Comment by annndruha** [comment]
Выяснили что БД валилась не из-за бота, но тем не менее от глобальной сессии избавился. #35
