### ISSUE TITLE
Настройка CI/CD

### ISSUE THREAD

**Issue by dyakovri** [profcomff/print-bot#6]
Надо 
- [x] Воткнуть в репку CI/CD конфиг поправленный, добавить Environment
- [x] #15
- [ ] Перекинуть в Caddy прокси
- [x] Отключить старый контейнер
- [x] Удалить БД app

Новые схемы для прода и теста бота и принтера уже создавал (кажется, они уже есть в environments, но если нет могу кинуть в личку)
```sql
create user srvc_prod_printer_api password '...';
create schema api_printer authorization srvc_prod_printer_api;
alter user srvc_prod_printer_api set search_path to api_printer;

create user srvc_prod_printer_bot password '...';
create schema bot_printer authorization srvc_prod_printer_bot;
alter user srvc_prod_printer_bot set search_path to bot_printer;

create user srvc_test_printer_api password '...';
create schema api_printer authorization srvc_test_printer_api;
alter user srvc_test_printer_api set search_path to api_printer;

create user srvc_test_printer_bot password '...';
create schema bot_printer authorization srvc_test_printer_bot;
alter user srvc_test_printer_bot set search_path to bot_printer;
```

**Comment by annndruha** [comment]
* Настроил CI/CD
* Дропнул `bot_printer ` - там было пусто. Используется `bot_vk_print`
* Контейнер отключил, но там вообще довольно много старых и тяжелых имаджей, вот их бы почистить
* @dyakovri Что такое Caddy прокси?
